### ISSUE TITLE
React-Navigation 5  如何做全局路由权限判断？

### ISSUE THREAD

**Issue by fangjunai** [wcly/blog#1]
React-Navigation 5  如何做全局路由权限判断？

**Comment by wcly** [comment]
- 可以考虑使用[onStateChange](https://reactnavigation.org/docs/navigation-container#onstatechange)或者[state](https://reactnavigation.org/docs/navigation-events)方法变化监听路由状态变化
- 或者可以直接写一个路由中转页面，跳转页面的时候通过这个页面统一处理权限校验和路由跳转
